[package]
name = "flappy-bevy"
version = "0.1.0"
edition = "2021"
authors = ["Devin Droddy <devin.droddy@gmail.com>"]

[dependencies]
avian2d = "0.2.1"
bevy = { version = "0.15.2", features = ["wayland"] }
rand = "0.9.0"

[features]
default = ["bevy/dynamic_linking"]
