[package]
name = "bevy-game"
version = "0.1.0"
edition = "2021"
authors = ["Devin Droddy <devin.droddy@gmail.com>"]

[dependencies]
bevy = { version = "0.15.2", features = ["wayland"] }

[features]
default = ["bevy/dynamic_linking"]
